# ─── Stage 1: Install dependencies ───────────────────────────────────────────
# We use a full Bun image just for installing packages.
# This stage is cached separately — if package.json doesn't change,
# Docker reuses this layer and skips the slow install step.
FROM oven/bun:1 AS deps
WORKDIR /app

COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile || bun install

# ─── Stage 2: Build the Next.js app ───────────────────────────────────────────
# Copies source code + node_modules from deps stage, then runs next build.
# Output mode "standalone" (set in next.config.mjs) produces a minimal
# self-contained folder under .next/standalone — no need to ship
# all of node_modules into the final image.
FROM oven/bun:1 AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ── Public vars (baked into client JS bundle — safe to have at build time) ───
ARG NEXT_PUBLIC_APP_URL=https://justbecausenetwork.com
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dh57hrdlc
ARG NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=akash001
ARG NEXT_PUBLIC_ALGOLIA_APP_ID=2AGPTOP6ZS
ARG NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=ca619041042c96e0c974ac6ef730ba63

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=$NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ENV NEXT_PUBLIC_ALGOLIA_APP_ID=$NEXT_PUBLIC_ALGOLIA_APP_ID
ENV NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=$NEXT_PUBLIC_ALGOLIA_SEARCH_KEY

# ── Server-side vars needed so Next.js can evaluate server modules during ─────
# ── static page generation (generateStaticParams / opengraph-image routes). ───
# ── These are ONLY used in the builder stage. The final runner image         ───
# ── (FROM node:22-alpine) copies only .next/standalone — these values are   ───
# ── NOT present in the image pushed to ECR. Real values come from ECS.       ───
ARG MONGODB_URI
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL=https://justbecausenetwork.com
ARG ELASTICSEARCH_URL
ARG ELASTICSEARCH_API_KEY
ARG NEXT_PUBLIC_STREAM_API_KEY
ARG STREAM_API_SECRET
ARG OPENAI_API_KEY
ARG GOOGLE_GENERATIVE_AI_API_KEY

ENV MONGODB_URI=$MONGODB_URI
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV ELASTICSEARCH_URL=$ELASTICSEARCH_URL
ENV ELASTICSEARCH_API_KEY=$ELASTICSEARCH_API_KEY
ENV NEXT_PUBLIC_STREAM_API_KEY=$NEXT_PUBLIC_STREAM_API_KEY
ENV STREAM_API_SECRET=$STREAM_API_SECRET
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV GOOGLE_GENERATIVE_AI_API_KEY=$GOOGLE_GENERATIVE_AI_API_KEY

# Skip secret scan — no .git inside Docker, secrets come from ECS at runtime
ENV SKIP_SECRET_SCAN=1
RUN bun run build

# ─── Stage 3: Production runner ───────────────────────────────────────────────
# This is the final image that actually runs on AWS ECS.
# It only contains the built output — no source code, no dev dependencies.
# Result: a lean ~200-300 MB image instead of 2+ GB.
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# next start needs a non-root user for security best practice
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone output (produced by output: 'standalone' in next.config)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# server.js is auto-generated by Next.js standalone output
CMD ["node", "server.js"]
